# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

test_that("check_data works", {
  
  object = check_primary_color_is_ok(c("Gray", "Cinnamon"))
  expect_true(object)
                             
})
