# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

test_that("get_message_fur_color works", {
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Cinnamon"), 
    regexp = "We will focus on Cinnamon squirrels"
  )
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Gray"), 
    regexp = "We will focus on Gray squirrels"
  )
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Black"), 
    regexp = "We will focus on Black squirrels"
  )
  
})

test_that("get_message_fur_color doesnt works", {
  
  expect_error(
   get_message_fur_color()
  )
  
})

test_that("check_study_activity graph", {
  object_df <- data_squirrels_act
  object_color <- "Gray"
  expected_output <- "ggplot"
  expect_true(inherits(study_activity(object_df,object_color)$graph,expected_output))
 }
)

test_that("check_study_activity df", {
  object_df <- data_squirrels_act
  object_color <- "Gray"
  expected_output <- "data.frame"
  expect_true(inherits(study_activity(object_df,object_color)$table,expected_output))
 }
)
