# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

#' Check the values of primary fur color
#'
#' @param string Character. A vector with the primary fur color.
#'
#' @return Boolean. TRUE if all colors are correct.
#' @export
#'
#' @examples
#' string = c("Gray", "Cinnamon")
#' check_primary_color_is_ok(string = string)
#' 
#' string = c("Gray")
#' check_primary_color_is_ok(string = string)
#' 
#' string = c("Black", "Cinnamon")
#' check_primary_color_is_ok(string = string)
check_primary_color_is_ok <- function(string) {
  all_colors_OK <- all(
    string %in% c("Gray", "Cinnamon", "Black", NA)
  )
  
  if(all_colors_OK == FALSE){
    stop("Color are not ok")
  } else {
    return(all_colors_OK)
  }
 
}
